### ISSUE TITLE
Laravel con Base de datos.

### ISSUE THREAD

**Issue by veritomis** [JosiasVasquez/itgrarte#1]
**Laravel con base de datos**
- Uno sobre Laravel que tiene mucha salida laboral. Proyecto simple, paso a paso, práctico. Creacion de tablas y servicios, pruebas unitarias.

**Comment by emmanuelpulidomx** [comment]
me parece muy interesante un curso sobre php y sobre larabel un framework  muy importante en el mundo del desarrollo web @JosiasVasquez #2

**Comment by JosiasVasquez** [comment]
@veritomis el nombre del curso debería estar en el título, solo una propuesta por cada issue, si quieres hacer más sugerencias puedes crear otro issue con tu siguiente propuesta.

Ya lo edité para dejar solo el primero, si puedes cambia el título y agrega el otro curso en un issue distinto.

**Comment by JosiasVasquez** [comment]
@veritomis @emmanuelpulidomx 
A mi me gustaría este curso también.

**Comment by JosiasVasquez** [comment]
@veritomis @emmanuelpulidomx 
A mi me gustaría este curso también.

**Comment by JosiasVasquez** [comment]
Tomo nota de la propuesta:
