### ISSUE TITLE
Curso de Redes

### ISSUE THREAD

**Issue by tiflotecnico** [JosiasVasquez/itgrarte#11]
me gustaría aprender estos temas de Redes:
• Fundamentos de una Red.
• Componentes y tipos de redes.
• Ancho de banda y medios de acceso.
• Técnicas de medición de redes y subredes.
• Analógico vs Digital.
• Protocolos de Red.
• Servicios de DNS, DHCP, WWW y FTP.
• Ethernet y Protocolo de Internet.
• Máscara de subred y su influencia en TCP/IP.
• Capas de transporte, VPN y acceso inalámbrico.
• Armar cables UTP según los estándares existentes.
• Capas del modelo OSI y modelo Internet.

**Comment by JosiasVasquez** [comment]
Suena interesante

**Comment by JosiasVasquez** [comment]
Tomo nota de la propuesta
