### ISSUE TITLE
Curso de PHP 

### ISSUE THREAD

**Issue by hugofloreshuertas** [JosiasVasquez/itgrarte#16]
Instalación del entorno de trabajo Apache Server
Etiquetas de apertura y cierre 
Instrucciones y estructuras.
Identación en PHP
Impresión en pantalla
array
Toda la guía elaborada la tengo en la laptop del trabajo...

**Comment by JosiasVasquez** [comment]
Me caería bien este curso, relacionado al de SQL estaría genial.

**Comment by JosiasVasquez** [comment]
Tomo nota de la propuesta
