### ISSUE TITLE
Curso sobre CiberSeguridad

### ISSUE THREAD

**Issue by 0restess** [JosiasVasquez/itgrarte#24]
Mi sugerencia es que el curso podria tratar sobre los siguientes apartados: 

Autenticación.
Amenaza persistente avanzada (APT).
El cloud computing.
Robo de datos.
Cifrado.
Seguridad para endpoint.
Firewall.
Proveedor de servicios de Internet (ISP).
Sistema de prevención de intrusiones (IPS).
Keylogger.
Malware.
Phishing.
Evaluación de riesgos.
Spyware.
Virus.

**Comment by JosiasVasquez** [comment]
Tomo nota de tu sugerencia, gracias.

**Comment by tinivelli** [comment]
Información para evitar inseguridad en redes sociales
