### ISSUE TITLE
Curso de SQL

### ISSUE THREAD

**Issue by orperedas** [JosiasVasquez/itgrarte#3]
Considero importante un curso de SQL, tiene mucha demanda tanto en desarrollo como en testing.

**Comment by JosiasVasquez** [comment]
Deja los issues abiertos por ahora @orperedas 

Gracias por la sugerencia, SQL sin duda sería algo importante para la administración de bases de datos.

**Comment by veritomis** [comment]
Si!

**Comment by jesicawulfson** [comment]
Coincido en que es muy importante tener conocimientos de SQL para programar o QA

**Comment by JosiasVasquez** [comment]
Tomo nota de la propuesta.
