### ISSUE TITLE
Curso Introducción a UX/UI

### ISSUE THREAD

**Issue by WalterCorrejidor** [JosiasVasquez/itgrarte#32]
El diseño UX es una herramienta muy importante para conocer cuáles son las necesidades de los usuarios. De esta manera, se pretenden adaptar los productos a los usuarios para poder satisfacer sus necesidades, cumpliendo con los objetivos de las empresas. La sigla UX refiere a la experiencia del usuario, por lo que el diseño de experiencia de usuario implica involucrar a los usuarios en las distintas etapas del proceso de creación de un producto. Por eso, en este curso introductorio de diseño UX/UI a distancia nos proponemos conocer cómo involucrar a los usuarios al momento de diseñar un producto.

**Comment by tinivelli** [comment]
Interesante. Un curso accesible del tema
