### ISSUE TITLE
Curso de Java Basico

### ISSUE THREAD

**Issue by Lucassistema** [JosiasVasquez/itgrarte#49]
Me gustria aprender sobre Java, conocer los aspectos básicos para uego continar por mi cuenta el aprendizaje. La duracion del curso podría ser dos a tres meses.

**Comment by Wined02** [comment]
seria muy bueno q luego de cada clase pongan como una tarea o una meta para la siguiente clase

**Comment by AlessandroCoccia** [comment]
Estoy interesado en que se imparta un curso de Java desde lo básico a lo más complejo del lenguaje, pasando por todas sus aplicaciones.
