### ISSUE TITLE
Auto aprendizaje con videos.

### ISSUE THREAD

**Issue by veritomis** [JosiasVasquez/itgrarte#5]
Un curso para aprender tecnicas de autoaprendizaje y seguir videos de clases de programacion tipo tutoriales sería muy util para todos.

**Comment by JosiasVasquez** [comment]
Tomo nota de la propuesta.

**Comment by tinivelli** [comment]
Crear un canal de youtube y subir videos (con lectores de pantalla) realizados por los mentores. Crear una lista de reproducción para cada curso. Actualizarlo con las preguntas realizadas en los diferentes cursos
