### ISSUE TITLE
introducción al script de jaws

### ISSUE THREAD

**Issue by facupa** [JosiasVasquez/itgrarte#6]
#Temario

1. Qué son los cripts.
2. Conociendo los archivos que pertenecen al script de jaws.
3. Conociendo el asistente del teclado.
4. Procesar combinaciones de teclas.
5. Conociendo el asistente de script de Jaws.
6. Crear scripts.
7. Partes de un scripts.
8. Como compilar un scripts.
9. Utilizar variables y constantes.
10. Crear y pronunciar mensajes.
11. Controlar el flujo del scripts mediante la toma de decisiones.
12. Entender las funciones.

El Objetivo de esta capacitación es que el alumno logre manejar el uso de script para luego poder implementarlo en cualquier ambito incluso en adaptaciones de puesto de trabajo.

**Comment by tiflotecnico** [comment]
@ interesante curso

**Comment by tiflotecnico** [comment]
interesante

**Comment by JosiasVasquez** [comment]
Tomo nota de la propuesta:

**Comment by tinivelli** [comment]
Como instalar scripts. Realizar los cursos con JAWS aparte de NVDA. Agregar teoría para ambos lectores si algo es diferente.
