### ISSUE TITLE
Curso de CSS

### ISSUE THREAD

**Issue by DanielaUnsain** [JosiasVasquez/itgrarte#8]
### **_POSIBLE TEMARIO:_**

- **INTRODUCCIÓN:**
Soporte de CSS en los navegadores.
Especificación oficial.
Funcionamiento básico de CSS.
Cómo incluir CSS en un documento XHTML.
Glosario básico.
Medios CSS.
Comentarios.
Sintaxis de la definición de cada propiedad CSS.

- **SELECTORES:**
Básicos.
Avanzados.
Agrupación de reglas.
Herencia.
Colisiones de estilos.

- **UNIDADES DE MEDIDA Y COLORES:**
Unidades de medida.
Colores.

- **MODELO DE CAJAS (box model):**
Anchura y altura.
Margen y relleno.
Bordes.
Margen, relleno, bordes y modelo de cajas.
Fondos.

- **POSICIONAMIENTO Y VISUALIZACIÓN:**
Tipos de elementos.
Posicionamiento.
Posicionamiento normal.
Posicionamiento relativo.
Posicionamiento absoluto.
Posicionamiento fijo.
Posicionamiento flotante.
Visualización.

**- TEXTO:**
Tipografía.
Texto.

- **ENLACES, IMÁGENES, LISTAS, TABLAS Y FORMULARIOS:**
Estilos básicos.
Estilos avanzados.

- **LAYOUT:**
Centrar una página horizontalmente.
Centrar una página verticalmente.
Estructura o layout.
Alturas/anchuras máximas y mínimas.
Estilos avanzados.

- **RECURSOS UTILES:**
Extensiones de Firefox.
Aplicaciones web.
Sitios web de inspiración.
Referencias y colecciones de recurso.

_**Sería importante que dicten un curso de CSS para complementar el ya otorgado de HTML.**_

**Comment by JosiasVasquez** [comment]
Tomo nota de la propuesta:

**Comment by tinivelli** [comment]
Otro de javascript para poder realizar webs interactivas
