### ISSUE TITLE
Curso básico de C#

### ISSUE THREAD

**Issue by GustavoGuanca** [JosiasVasquez/itgrarte#9]
### **Posible temario del Curso básico de C#:**
 

- [ ] _Unidad I._ Algoritmos, variables. Tipos de datos. Creación del primer programa en Visual Studio.

- [ ] _Unidad II._ Operadores aritméticos, variables numéricas, asignaciones, palabras reservadas del lenguaje C#.

- [ ] _Unidad III._ Condicional If then else: operadores relacionales, condiciones simples, condiciones anidadas, operadores lógicos.

- [ ] _Unidad IV._ Condicional Switch: Concatenación de condiciones.

- [ ] _Unidad V._ Estructuras repetitivas: Ciclo For, While, Do while.

- [ ] _Unidad VI._ Vectores. Ordenamientos.

- [ ] _Unidad VII._ Funciones. Trabajo Final.

**Me gustaría que se imparta este curso porque siento que es un lenguaje de programación muy potente en el que se pueden hacer muchísimos proyectos interesantes.**

**Comment by JosiasVasquez** [comment]
Tomo nota de la propuesta
